Update JenkinsFile

diff --git a/spring-boot-app/JenkinsFile b/spring-boot-app/JenkinsFile
--- a/spring-boot-app/JenkinsFile
+++ b/spring-boot-app/JenkinsFile
@@ -29,22 +29,33 @@ pipeline {
         }
       }
     }
-    stage('Build and Push Docker Image') {
-      environment {
+   stage('Build and Push Docker Image') {
+    environment {
         DOCKER_IMAGE = "herosk/custom-app:${BUILD_NUMBER}"
-        // DOCKERFILE_LOCATION = "spring-boot-app/Dockerfile"
         REGISTRY_CREDENTIALS = credentials('docker-cred')
-      }
-      steps {
+    }
+    steps {
         script {
-            sh 'cd spring-boot-app && docker build -t ${DOCKER_IMAGE} .'
+            sh '''
+                if [ ! -d "spring-boot-app" ]; then
+                  echo "Directory spring-boot-app not found!"
+                  exit 1
+                fi
+                cd spring-boot-app && ls -l Dockerfile && docker build -t ${DOCKER_IMAGE} .
+            '''
             def dockerImage = docker.image("${DOCKER_IMAGE}")
+
             docker.withRegistry('https://index.docker.io/v1/', "docker-cred") {
-                dockerImage.push()
+                try {
+                    dockerImage.push()
+                } catch (Exception e) {
+                    error("Docker image push failed: ${e}")
+                }
             }
         }
-      }
     }
+}
+
     stage('Update Deployment File') {
         environment {
             GIT_REPO_NAME = "jenkins-with-sonar"
